In [5]:
import numpy as np
import tensorflow as tf

### Creating Stacked LSTM

In [9]:
cells = []

# First LSTM layer
cell_size_1 = 4 #4 hidden nodes
cell1 = tf.keras.layers.LSTMCell(cell_size_1)
cells.append(cell1)

# Second LSTM layer
cell_size_2 = 5 #5 hidden nodes
cell2 = tf.keras.layers.LSTMCell(cell_size_2)
cells.append(cell2)

stacked_lstm =  tf.keras.layers.StackedRNNCells(cells)
lstm_layer= tf.keras.layers.RNN(stacked_lstm ,return_sequences=True, return_state=True)

### Create Data Examples

In [7]:
#Batch size x time steps x features.
sample_input = [[[1,2,3,4,3,2], [1,2,1,1,1,2],[1,2,2,2,2,2]],[[1,2,3,4,3,2],[3,2,2,1,1,2],[0,0,0,0,3,2]]]

batch_size = 2
time_steps = 3
features = 6
new_shape = (batch_size, time_steps, features)

x = tf.constant(np.reshape(sample_input, new_shape), dtype = tf.float32)

### Show Training Output

In [8]:
output, final_memory_state, final_carry_state  = lstm_layer(x)

print('Output : ', tf.shape(output))
print('Memory : ',tf.shape(final_memory_state))
print('Carry state : ',tf.shape(final_carry_state))

Output :  tf.Tensor([2 3 5], shape=(3,), dtype=int32)
Memory :  tf.Tensor([2 2 4], shape=(3,), dtype=int32)
Carry state :  tf.Tensor([2 2 5], shape=(3,), dtype=int32)
